name: Perform code checkings

on:
  push:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

  pull_request:
    branches: '*'
    tags: '*'
    paths-ignore: '**.md'

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to gitexp
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.32.x

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Cache pnpm store
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
            ~/.pnpm-store
          key: ${{ env.preffix }}-cache-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ env.preffix }}-cache-${{ env.cache-name }}-
            ${{ env.preffix }}-cache-
            ${{ env.preffix }}-
        env:
          cache-name: code-check
          preffix: ${{ runner.os }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

      - name: Check TS build
        run: pnpm run build:js

      - name: Check linter rules
        run: pnpm run check:lint

      - name: Check code style
        run: pnpm run check:style

      - name: Check for duplicated code
        run: pnpm run check:duplicated

      - name: Run tests
        run: pnpm test
