name: Perform code checkings

on:
  push:
    branches: ['*']
    tags: ['*']
    paths-ignore: ['**.md']

  pull_request:
    branches: ['*']
    tags: ['*']
    paths-ignore: ['**.md']

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Cache npm modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Check TS build
        run: npm run build:types

      - name: Check code style
        run: npm run check:style

      - name: Check for duplicated code
        run: npm run check:duplicated

      - name: Run tests
        run: npm test
